PW/projekt/ContainersApp/ContainersWebApp/Models/Container.cs
using ContainersApp.Core;
using ContainersApp.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace ContainersWebApp.Models
{
    public class Container : IContainer
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [Range(1900, 2100)]
        public int ProductionYear { get; set; }

        [Required]
        public ContainerType Type { get; set; }

        public IProducer? Producer { get; set; } = null;
        
        [Required]
        public int ProducerId { get; set; }
    }
}

PW/projekt/ContainersApp/ContainersWebApp/Models/ErrorViewModel.cs
namespace ContainersWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PW/projekt/ContainersApp/ContainersWebApp/Models/Producer.cs
using ContainersApp.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace ContainersWebApp.Models
{
    public class Producer : IProducer
    {
        public int Id { get; set; }
        
        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        public string Address { get; set; }
    }
}

PW/projekt/ContainersApp/ContainersWebApp/Controllers/ContainersController.cs
using ContainersApp.BLC;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ContainersWebApp.Controllers
{
    public class ContainersController : Controller
    {
        private readonly BLC _blc;
        public ContainersController(BLC blc)
        {
            _blc = blc;
        }
        public IActionResult Index(string? searchString)
        {
            if (searchString != null)
            {
                return View(_blc.GetContainersByName(searchString));
            }
            return View(_blc.GetAllContainers());
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var container = _blc.GetContainer((int)id);
            if (container == null)
            {
                return NotFound();
            }

            return View(container);
        }

        public IActionResult Create()
        {
            ViewBag.Producers = new SelectList(_blc.GetAllProducers(), "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,ProductionYear,ProducerId,Type")] Models.Container container)
        {
            if (ModelState.IsValid)
            {
                container.Producer = _blc.GetProducer(container.ProducerId);
                _blc.AddContainer(container);
                return RedirectToAction(nameof(Index));
            }
            return View(container);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var container = _blc.GetContainer((int)id);
            if (container == null)
            {
                return NotFound();
            }

            ViewBag.Producers = new SelectList(_blc.GetAllProducers(), "Id", "Name");

            Models.Container containerModel = new Models.Container()
            {
                Id = container.Id,
                Name = container.Name,
                Producer = container.Producer,
                ProducerId = container.Producer.Id,
                ProductionYear = container.ProductionYear,
                Type = container.Type
            };

            return View(containerModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,ProductionYear,ProducerId,Type")] Models.Container container)
        {
            if (id != container.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                container.Producer = _blc.GetProducer(container.ProducerId);
                _blc.UpdateContainer(container);
                return RedirectToAction(nameof(Index));
            }

            return View(container);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var container = _blc.GetContainer((int)id);
            if (container == null)
            {
                return NotFound();
            }

            return View(container);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _blc.DeleteContainer(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

PW/projekt/ContainersApp/ContainersWebApp/Controllers/HomeController.cs
using ContainersWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ContainersWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PW/projekt/ContainersApp/ContainersWebApp/Controllers/ProducersController.cs
using ContainersApp.BLC;
using Microsoft.AspNetCore.Mvc;

namespace ContainersWebApp.Controllers
{
    public class ProducersController : Controller
    {
        private readonly BLC _blc;
        public ProducersController(BLC blc)
        {
            _blc = blc;
        }
        public IActionResult Index()
        {
            return View(_blc.GetAllProducers());
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producer = _blc.GetProducer((int)id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,Address")] Models.Producer producer)
        {
            if (ModelState.IsValid)
            {
                _blc.AddProducer(producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producer = _blc.GetProducer((int)id);
            if (producer == null)
            {
                return NotFound();
            }

            Models.Producer producerModel = new Models.Producer()
            {
                Id = producer.Id,
                Name = producer.Name,
                Address = producer.Address
            };

            return View(producerModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Address")] Models.Producer producer)
        {
            if (id != producer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _blc.UpdateProducer(producer);
                return RedirectToAction(nameof(Index));
            }

            return View(producer);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producer = _blc.GetProducer((int)id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _blc.DeleteProducer(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

PW/projekt/ContainersApp/ContainersWebApp/Views/Containers/Create.cshtml
@model ContainersWebApp.Models.Container

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Container</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionYear" class="control-label"></label>
                <input asp-for="ProductionYear" class="form-control" />
                <span asp-validation-for="ProductionYear" class="text-danger"></span>
            </div>
			<div class="form-group">
                <label asp-for="ProducerId" class="control-label"></label>
                @Html.DropDownListFor(model => model.ProducerId, (SelectList)ViewBag.Producers, "Select Producer", new { @class = "form-control" })
                <span asp-validation-for="ProducerId" class="text-danger"></span>
            </div>
		   <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                @Html.DropDownListFor(model => model.Type, new SelectList(Enum.GetValues(typeof(ContainersApp.Core.ContainerType))), "Select Container Type", new { @class = "form-control" })
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PW/projekt/ContainersApp/ContainersWebApp/Views/Containers/Delete.cshtml
@model ContainersApp.Interfaces.IContainer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IContainer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductionYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PW/projekt/ContainersApp/ContainersWebApp/Views/Containers/Details.cshtml
@model ContainersApp.Interfaces.IContainer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>IContainer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductionYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

PW/projekt/ContainersApp/ContainersWebApp/Views/Containers/Edit.cshtml
@model ContainersWebApp.Models.Container

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Container</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionYear" class="control-label"></label>
                <input asp-for="ProductionYear" class="form-control" />
                <span asp-validation-for="ProductionYear" class="text-danger"></span>
            </div>
			<div class="form-group">
                <label asp-for="ProducerId" class="control-label"></label>
                @Html.DropDownListFor(model => model.ProducerId, (SelectList)ViewBag.Producers, "Select Producer", new { @class = "form-control" })
                <span asp-validation-for="ProducerId" class="text-danger"></span>
            </div>
		   <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                @Html.DropDownListFor(model => model.Type, new SelectList(Enum.GetValues(typeof(ContainersApp.Core.ContainerType))), "Select Container Type", new { @class = "form-control" })
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PW/projekt/ContainersApp/ContainersWebApp/Views/Containers/Index.cshtml
@model IEnumerable<ContainersApp.Interfaces.IContainer>

@{
    ViewData["Title"] = "Index";
}

<h1>Containers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm("Index", "Containers", FormMethod.Get))
{
	<p>
		Search: @Html.TextBox("searchString")
		<input type="submit" value="Search" />
	</p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductionYear)
            </th>
            <th>
                Producer Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductionYear)
            </td>
            <th>
                @Html.DisplayFor(model => item.Producer.Name)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

PW/projekt/ContainersApp/ContainersWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

PW/projekt/ContainersApp/ContainersWebApp/Views/Producers/Create.cshtml
@model ContainersWebApp.Models.Producer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PW/projekt/ContainersApp/ContainersWebApp/Views/Producers/Delete.cshtml
@model ContainersApp.Interfaces.IProducer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PW/projekt/ContainersApp/ContainersWebApp/Views/Producers/Details.cshtml
@model ContainersApp.Interfaces.IProducer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

PW/projekt/ContainersApp/ContainersWebApp/Views/Producers/Edit.cshtml
@model ContainersWebApp.Models.Producer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Producer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PW/projekt/ContainersApp/ContainersWebApp/Views/Producers/Index.cshtml
@model IEnumerable<ContainersApp.Interfaces.IProducer>

@{
    ViewData["Title"] = "Index";
}

<h1>Producers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

PW/projekt/ContainersApp/ContainersWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContainersWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContainersWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContainersWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Containers" asp-action="Index">Containers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producers" asp-action="Index">Producers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ContainersWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>